name: Publish

on:
  release:
    types: [created]

jobs:
  metadata-publish:
    name: Publish Metadata
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish Metadata
        run: ./gradlew publish --info -Pbuild_type=METADATA -Pbintray_api_key=${{ secrets.BINTRAY_API_KEY }}
  non-native-publish:
    name: Publish JVM, Android, JS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish JVM, Android, JS
        run: ./gradlew publish --info -Pbuild_type=NON_NATIVE -Pbintray_api_key=${{ secrets.BINTRAY_API_KEY }}
  linux-publish:
    name: Publish Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish Linux
        run: ./gradlew publish --info -Pbuild_type=LINUX -Pbintray_api_key=${{ secrets.BINTRAY_API_KEY }}
  ios-publish:
    name: Publish iOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish iOS
        run: ./gradlew publish -Pbuild_type=IOS -Pbintray_api_key=${{ secrets.BINTRAY_API_KEY }}
  macos-publish:
    name: Publish imacOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish macOS
        run: ./gradlew publish --info -Pbuild_type=MAC_OS -Pbintray_api_key=${{ secrets.BINTRAY_API_KEY }}
